name: yummap
description: "La carte aux tresors du Paris culinaire."
version: 2.0.0+2
environment:
  sdk: '>=3.2.6 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/custom_map.json

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  flutter_map: ^4.0.0
  latlng: any
  http: ^0.13.3
  chewie: ^1.2.2
  video_player: ^2.4.2
  carousel_slider: ^4.0.0
  logger: ^2.0.2+1
  glassmorphism: ^3.0.0
  url_launcher: ^6.0.9
  geolocator: ^8.0.1
  flutter_native_splash: any  # Ajout du package flutter_native_splash
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
