// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-8MazRr7XbmG66wOMge298V2aQCo_lw',
    appId: '1:949394398517:web:47074e8fd3490d1b84407c',
    messagingSenderId: '949394398517',
    projectId: 'yummap-app',
    authDomain: 'yummap-app.firebaseapp.com',
    storageBucket: 'yummap-app.firebasestorage.app',
    measurementId: 'G-HKDY3NNFPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuTao0G_Vi3LvHxqHKRjwZZV6CBwot5g',
    appId: '1:949394398517:android:05a548bc29991e6984407c',
    messagingSenderId: '949394398517',
    projectId: 'yummap-app',
    storageBucket: 'yummap-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-1KORSyfFx9M2wGqK4FaEKwe3tw_5E0',
    appId: '1:949394398517:ios:cae9050b688b4d3984407c',
    messagingSenderId: '949394398517',
    projectId: 'yummap-app',
    storageBucket: 'yummap-app.firebasestorage.app',
    iosBundleId: 'com.domain.yummap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-1KORSyfFx9M2wGqK4FaEKwe3tw_5E0',
    appId: '1:949394398517:ios:cae9050b688b4d3984407c',
    messagingSenderId: '949394398517',
    projectId: 'yummap-app',
    storageBucket: 'yummap-app.firebasestorage.app',
    iosBundleId: 'com.domain.yummap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-8MazRr7XbmG66wOMge298V2aQCo_lw',
    appId: '1:949394398517:web:804b0ce6dd7f5d9784407c',
    messagingSenderId: '949394398517',
    projectId: 'yummap-app',
    authDomain: 'yummap-app.firebaseapp.com',
    storageBucket: 'yummap-app.firebasestorage.app',
    measurementId: 'G-SZKPYH27CW',
  );

}